apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: k8s-presentation
    color: green
  name: k8s-presentation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-presentation
        color: green
    spec:
      containers:
      - image: matheussampaio/k8s-presentation:beta-2
        name: k8s-presentation
        env:
        - name: BODY_FILENAME
          value: "templates/body.html"
        envFrom:
        - configMapRef:
            name: k8s-presentation-envs
        volumeMounts:
        - name: k8s-presentation-volume
          mountPath: /opt/app/templates
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 2
      volumes:
      - name: k8s-presentation-volume
        configMap:
          name: k8s-presentation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-presentation
data:
  body.html: |
    <div>
      Config Map also rocks!

      Kubernetes does the job for us. :D
    </div>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-presentation-envs
data:
  CONFIG_API_URL: "api-staging"
  MOCK_AGGREGATION_API: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-presentation
spec:
  selector:
    app: k8s-presentation
    color: green
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30001
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: k8s-presentation
    color: blue
  name: k8s-presentation-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-presentation
        color: blue
    spec:
      containers:
      - image: matheussampaio/k8s-presentation:beta-2
        name: k8s-presentation
        env:
        - name: BODY_FILENAME
          value: "templates/body.html"
        envFrom:
        - configMapRef:
            name: k8s-presentation-envs
        volumeMounts:
        - name: k8s-presentation-volume
          mountPath: /opt/app/templates
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 2
      volumes:
      - name: k8s-presentation-volume
        configMap:
          name: k8s-presentation-blue
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-presentation-blue
data:
  body.html: |
    <div style="background: #00f; color: #fff">
      COLOR = BLUE
    </div>
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-presentation-blue
spec:
  selector:
    app: k8s-presentation
    color: blue
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-presentation-green
spec:
  selector:
    app: k8s-presentation
    color: green
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-presentation-both
spec:
  selector:
    app: k8s-presentation
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30004
