apiVersion: v1
kind: Service
metadata:
  name: k8s-presentation-prod
  color: green
spec:
  selector:
    app: k8s-presentation
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-presentation-both
spec:
  selector:
    app: k8s-presentation
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30004
