apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: k8s-presentation
  name: k8s-presentation
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-presentation
    spec:
      containers:
      - image: matheussampaio/k8s-presentation:beta-2
        name: k8s-presentation
        env:
        - name: BODY_FILENAME
          value: "templates/body.html"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-presentation
spec:
  selector:
    app: k8s-presentation
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30001
